- name: Install package
  community.general.pacman:
    name: redis
    state: present
  become: yes
  become_user: root
  become_method: sudo

- name: Check for redis server
  register: redis_running
  command: systemctl is-active redis --quiet
  failed_when:
    - redis_running.rc != 0
    - redis_running.rc != 3

- name: Startup with systemctl
  command: systemctl enable redis.service
  become: yes
  become_user: root
  become_method: sudo
  when: redis_running.rc == 3
