- name: Set up local workstation
  hosts: local
  roles:
    - role: git
      tags:
        - git
    - role: pacman
      tags:
        - pacman
    - role: zsh
      tags:
        - zsh
    - role: fzf
      tags:
        - fzf
    - role: vim
      tags:
        - vim
    # TODO: kitty
    # - role: tmux
    #   tags:
    #     - tmux
    - role: asdf
      tags:
        - asdf
    - role: python
      tags:
        - python
    - role: golang
      tags:
        - golang
    - role: ruby
      tags:
        - ruby
    - role: node
      tags:
        - node
    - role: redis
      tags:
        - redis
