# Configuration
- name: Check if settings.json exists
  stat: path="{{dotfiles_user_home}}/.config/VSCodium/User/settings.json"
  register: settings_stat
  failed_when: False

- name: Backup settings.json
  command: mv {{dotfiles_user_home}}/.config/VSCodium/User/settings.json {{dotfiles_user_home}}/.config/VSCodium/User/settings.json.bak
  args:
    creates: "{{dotfiles_user_home}}/.config/VSCodium/User/settings.json.bak"
  when: settings_stat.stat.exists
- name: Check config directory exists
  stat:
    path: "{{dotfiles_user_home}}/.config/VSCodium/User"
  register: codium_config_dir
  when: settings_stat.stat.exists == False
- name: "Ansible Create directory if not exists"
  file:
    path: "{{dotfiles_user_home}}/.config/VSCodium/User"
    state: directory
  when:
    - settings_stat.stat.exists == False
    - codium_config_dir.stat.exists == false

- name: Symlink settings.json
  file:
    src: "{{ dotfiles_home }}/roles/codium/files/settings.json"
    dest: "{{dotfiles_user_home}}/.config/VSCodium/User/settings.json"
    state: link

- name: Install extension
  command: "codium --install-extension {{ item }}"
  loop: "{{ extensions }}"
