# TODO: install yay

- name: Clone yay
  register: clone_yay
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: "/tmp/yay"
- name: Install yay
  when: clone_yay.changed
  shell: |
    cd /tmp/yay
    makepkg -si --noconfirm
- name: Install package from AUR
  command: yay -S --noconfirm {{ item }}
  loop: "{{ packages }}"
- name: Remove packages
  command: yay -R --noconfirm {{ item }}
  loop: "{{ remove_packages }}"
