- name: Run the equivalent of "pacman -Syu" as a separate step
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  when: package_upgrade
  become: yes
  become_user: root
  become_method: sudo

- name: Install package from repo
  community.general.pacman:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ packages }}"

- name: Remove packages
  community.general.pacman:
    name: "{{ item }}"
    state: absent
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ remove_packages }}"
